## cd
name: setup/signing
description: |
  Installs pfx components to be compiled.

## requires:
## <- env.OP_SERVICE_ACCOUNT_TOKEN

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash

    - uses: KamaranL/1password-load-secrets-action@v1
      with:
        export-env: false
      env:
        cer: op://Integrations/kamaranl_at_kamaranl_dot_vip.p12/public-key
        key: op://Integrations/kamaranl_at_kamaranl_dot_vip.p12/private-key
        pass: op://Integrations/kamaranl_at_kamaranl_dot_vip.p12/password
        int_ca: op://Integrations/kamaranl_at_kamaranl_dot_vip.p12/intermediate-ca
        root_ca: op://Integrations/kamaranl_at_kamaranl_dot_vip.p12/root-ca
      id: op-pfx

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        CER: ${{ steps.op-pfx.outputs.cer }}
        KEY: ${{ steps.op-pfx.outputs.key }}
        PASS: ${{ steps.op-pfx.outputs.pass }}
        INT_CA: ${{ steps.op-pfx.outputs.int_ca }}
        ROOT_CA: ${{ steps.op-pfx.outputs.root_ca }}

    - if: runner.os != 'Windows'
      run: $GITHUB_ACTION_PATH/post.sh
      shell: bash
      env:
        PFX_PASS: ${{ steps.op-pfx.outputs.pass }}

    - if: runner.os == 'Windows'
      run: '& $env:GITHUB_ACTION_PATH/Post.ps1'
      shell: pwsh
      env:
        PFX_PASS: ${{ steps.op-pfx.outputs.pass }}

    - if: runner.os == 'Windows'
      uses: KamaranL/add-signtool-action@v1

## results:
## -> env.PFX_DIR
## -> env.PFX_ID
