name: setup-cd
description: ''
runs:
  using: composite
  steps:
    - uses: KamaranL/actions/setup/job@v0
      with:
        checkout: |
          fetch-depth=0
          fetch-tags=true

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        WFR_REF: ${{ github.event.workflow_run.referenced_workflows[0].ref }}
      id: main
