name: cd-npm
description: ''
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      id: pre

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      id: main
