name: exec-issue
description: ''

runs:
  using: composite
  steps:
    - uses: KamaranL/actions/setup@v0

    - uses: KamaranL/actions/checks@v0
      with:
        github: ci-label
      id: checks

    - if: fromJson(steps.checks.outputs.github).ci-label == false
      run: |
        : # create ci label
        gh label create ci --description "Workflow-related" --color 5319E7
      shell: bash

    - run: |
        : # write job output to log
        LOG_TEMP='${{ fromJson(steps.checks.outputs.path).log }}'
        [ ! -d "$LOG_TEMP" ] && mkdir -p "$LOG_TEMP"
        gh run view $GITHUB_RUN_ID -v --log-failed --attempt $GITHUB_RUN_ATTEMPT >"$LOG_TEMP/$GITHUB_WORKFLOW-$GITHUB_RUN_ID.GITHUB_RUN_ATTEMPT.log"
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: logs
        path: ${{ runner.temp }}/.log/*
        retention-days: 10
        compression-level: 9
      id: logs

    - run: |
        : # create issue
        gh issue create \
            --assignee $GITHUB_TRIGGERING_ACTOR \
            --label ci \
            --title "$GITHUB_WORKFLOW on $GITHUB_HEAD_REF ($GITHUB_RUN_ID)" \
            --body "$(
                cat <<DOC
        Attempt # $GITHUB_RUN_ATTEMPT
        - [ ] Review [logs](${{ steps.logs.outputs.artifact-url }})
        - [ ] Mention findings
        DOC
            )"
      shell: bash

    - run: |
        : # cleanup
        rm -rf '${{ fromJson(steps.checks.outputs.path).log }}'
      shell: bash
