name: cd-release
description: ''
inputs:
  assets:
    description: ''

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      id: pre

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        INPUT_ASSETS: ${{ inputs.assets }}
      id: main
