name: cd-release
description: ''
inputs:
  assets:
    description: ''

runs:
  using: composite
  steps:

    - run: |
        echo -e "$WORKFLOW_REF" | grep -oE '[0-9]{1,}'
        exit 1
      shell: bash
      env:
        WORKFLOW_REF: ${{ github.event.workflow_run.referenced_workflows[0].ref }}

    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      env:
        WORKFLOW_RUN_BASE_REF: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
      id: pre

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        INPUT_ASSETS: ${{ inputs.assets }}
        CI_TAG: ${{ steps.pre.outputs.ci-tag }}
      id: main
