name: cd

# continuously delivers packaged codebase

on:
  workflow_run:
    workflows: [ci]
    types: completed

concurrency: ${{ github.event_name }}-${{ github.workflow }}
defaults:
  run:
    shell: bash

jobs:
  cd:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TOKEN }}
    steps:
      - uses: KamaranL/actions/setup/job@v0
        with:
          checkout: |
            fetch-depth=0
            fetch-tags=true

      - uses: KamaranL/actions/setup/cd@v0

      - uses: KamaranL/actions/exec/cd/release@v0
        continue-on-error: true

      - uses: KamaranL/actions/exec/cd/npm@v0
        continue-on-error: true


