name: cd

# continuously delivers packaged codebase

on:
  workflow_run:
    workflows: [ci]
    types: completed

concurrency: ${{ github.event_name }}-${{ github.workflow }}
defaults:
  run:
    shell: bash

jobs:
  cd:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_TOKEN }}
    steps:
      - uses: KamaranL/actions/setup/job@v0
        with:
          checkout: |
            fetch-depth=0
            fetch-tags=true

      - uses: KamaranL/actions/setup/cd/dotnet_core@v0
        with:
          release-identifiers: |
            win-x64
            osx-x64
            linux-x64
        id: publish

      - uses: KamaranL/actions/exec/cd/release@v0
        with:
          assets: ${{ steps.publish.outputs.dist }}
        continue-on-error: true

      # - uses: KamaranL/actions/exec/cd/nuget@v0 (TBA?)


