name: exec-issue
description: ''
inputs:
  workflow-run:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - uses: KamaranL/actions/setup@v0
      with:
        no-repo: true

    - uses: KamaranL/actions/checks@v0
      with:
        github: ci-label
      id: checks

    - if: fromJson(steps.checks.outputs.github).ci-label == false
      run: |
        : # create ci label
        gh label create ci --description "Workflow-related" --color 5319E7 --repo "$GITHUB_REPOSITORY"
      shell: bash

    - run: |
        : # write job output to log
        LOG_TEMP='${{ fromJson(steps.checks.outputs.path).log }}'
        [ ! -d "$LOG_TEMP" ] && mkdir -p "$LOG_TEMP"
        gh run view $WORKFLOW_RUN_ID -v --log-failed \
            --attempt $WORKFLOW_RUN_ATTEMPT \
            --repo "$GITHUB_REPOSITORY" >"$LOG_TEMP/$WORKFLOW_RUN-$WORKFLOW_RUN_ID.$WORKFLOW_RUN_ATTEMPT.log"
      shell: bash
      env:
        WORKFLOW_RUN: ${{ fromJson(inputs.workflow-run).name }}
        WORKFLOW_RUN_ATTEMPT: ${{ fromJson(inputs.workflow-run).run_attempt }}
        WORKFLOW_RUN_ID: ${{ fromJson(inputs.workflow-run).id }}

    - uses: actions/upload-artifact@v4
      with:
        name: logs
        path: ${{ runner.temp }}/.log/*
        retention-days: 10
        compression-level: 9
      id: logs

    - run: |
        : # create issue
        gh issue create \
            --assignee $GITHUB_TRIGGERING_ACTOR \
            --label ci \
            --title "🔴 ${WORKFLOW_RUN^} #${WORKFLOW_RUN_NUMBER}: $WORKFLOW_RUN_EVENT" \
            --body "$(
                cat <<DOC
        Attempt: $WORKFLOW_RUN_ATTEMPT

        Branch: TBD

        - [ ] Review [logs](${{ steps.logs.outputs.artifact-url }})
        - [ ] Mention findings
        DOC
            )" \
            --repo "$GITHUB_REPOSITORY"
      shell: bash
      env:
        WORKFLOW_RUN: ${{ fromJson(inputs.workflow-run).name }}
        WORKFLOW_RUN_ATTEMPT: ${{ fromJson(inputs.workflow-run).run_attempt }}
        WORKFLOW_RUN_CONCLUSION: ${{ fromJson(inputs.workflow-run).conclusion }}
        WORKFLOW_RUN_EVENT: ${{ fromJson(inputs.workflow-run).event }}
        WORKFLOW_RUN_ID: ${{ fromJson(inputs.workflow-run).id }}
        WORKFLOW_RUN_NUMBER: ${{ fromJson(inputs.workflow-run).run_number }}

    - run: |
        : # cleanup
        rm -rf '${{ fromJson(steps.checks.outputs.path).log }}'
      shell: bash
