name: issue
description: ''
runs:
  using: composite
  steps:
    - uses: KamaranL/actions/setup/job@v0

    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      env:
        WFR: ${{ github.event.workflow_run.name }}
        WFR_ATTEMPT: ${{ github.event.workflow_run.run_attempt }}
        WFR_ID: ${{ github.event.workflow_run.id }}
      id: pre

    - run: |
        ls -lA $RUNNER_TEMP/.log
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: logs
        path: ${{ runner.temp }}/.log/*
        retention-days: 10
        compression-level: 9
      id: logs

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        LOG_URL: ${{ steps.logs.outputs.artifact-url }}
        WFR: ${{ github.event.workflow_run.name }}
        WFR_ATTEMPT: ${{ github.event.workflow_run.run_attempt }}
        WFR_BASE_REF: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
        WFR_BASE_SHA: ${{ github.event.workflow_run.pull_requests[0].base.sha }}
        WFR_BRANCH: ${{ github.event.workflow_run.head_branch }}
        WFR_COMMITTER: '${{ github.event.workflow_run.head_commit.committer.name }} <${{ github.event.workflow_run.head_commit.committer.email }}>'
        WFR_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        WFR_EVENT: ${{ github.event.workflow_run.event }}
        WFR_FILE: ${{ github.event.workflow_run.html_url }}/workflow
        WFR_HEAD_REF: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
        WFR_HEAD_SHA: ${{ github.event.workflow_run.pull_requests[0].head.sha }}
        WFR_ID: ${{ github.event.workflow_run.id }}
        WFR_NUMBER: ${{ github.event.workflow_run.run_number }}
        WFR_PATH: ${{ github.event.workflow_run.path }}
        WFR_SHA: ${{ github.event.workflow_run.head_sha }}
      id: main
