name: test

# performs testing against codebase

on:
  workflow_call:
  pull_request:
    types: [synchronize, edited]
    paths:
      - '!VERSION.txt'
      - '!package.json'
      - '!package-lock.json'

concurrency: ${{ github.event_name }}-${{ github.job }}
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: npm i -g npm@latest

      - run: npm ci

      - run: npm test
