## cd
name: sign-code
description: |

## requires:
## <- env.PFX_DIR
## <- env.PFX_ID

inputs:
  in:
    required: true
    description: |
      Directory path containing build artifacts, or directory path containing subdirectories that each contain build artifacts.
      Directory name(s) **must** be in rid (release identifier) format.

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash

    - if: runner.os != 'Windows'
      run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        INPUTS_IN: ${{ inputs.in }}

    - if: runner.os == 'Windows'
      run: '& $env:GITHUB_ACTION_PATH/Main.ps1'
      shell: pwsh
      env:
        INPUTS_IN: ${{ inputs.in }}
