name: setup/release
description: ''
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        WFR_REF: ${{ github.event.workflow_run.referenced_workflows[0].ref }}
