name: ci
description: ''
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}
      id: pre

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
      id: main
