name: ci
description: ''
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      id: pre
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      id: main
