name: watch
description: ''
runs:
  using: composite
  steps:
    - uses: KamaranL/actions/setup@v0

    - run: |
        : # check watched files
        WATCHED=(
            pull_request
            issue
        )
        for item in "${WATCHED[@]}"; do
            file=".github/.open_$item"
            val=false
            [ -f "$file" ] && {
                val=true
                rm -rf "$file"
                ran=true
            }
            echo "open-$item=$val" >>"$GITHUB_OUTPUT"
        done
        echo "ran=${ran:-false}" >>"$GITHUB_OUTPUT"
      shell: bash
      id: watched

    - if: fromJson(steps.watched.outputs.open-pull_request) == true
      run: |
        echo we are opening a pull_request
      shell: bash

    - if: fromJson(steps.watched.outputs.open-issue) == true
      run: |
        echo we are opening an issue
      shell: bash

    - if: fromJson(steps.watched.outputs.ran) == true
      run: |
        echo it ran
      shell: bash
