name: 'release'
description: ''
runs:
  using: composite
  steps:
    - run: |
        echo "$PWD"
        realpath "$PWD"
      shell: bash

    # - if: ${{ github. }}
      # uses: actions/checkout@v4

    - uses: actions/checkout@v4

    - run: |
        echo "$PWD"
        realpath "$PWD"
      shell: bash
