## ci
name: commit-merge
description: |
  1. Amend commit
  2. Tag commit
  3. Push amended commit, as well as new/updated tags, to origin\

## requires:
## <- env.GH_TOKEN
## <- env.CI_VERSION
## <- env.CI_SOURCE_BRANCH
## <- KamaranL/actions/setup: [checkout, identity, semver]

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash

    - run: echo "$CI_VERSION" >VERSION.txt
      shell: bash

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
