## ci
name: setup/semver
description: |
  Calculate semver.

## requires:
## <- ${github.workspace}/VERSION.txt

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      env:
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      id: pre

    - uses: gittools/actions/gitversion/setup@v0.13
      with:
        versionSpec: 5.x

    - uses: gittools/actions/gitversion/execute@v0.13
      with:
        disableCache: true
        useConfigFile: true
        configFilePath: ${{ github.action_path }}/GitVersion.yml
        overrideConfig: ${{ steps.pre.outputs.overrideConfig }}
        additionalArguments: ${{ steps.pre.outputs.additionalArguments }}

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash

## results:
## -> env.CI_NUGET
## -> env.CI_NUGET_VERSION
## -> env.CI_VERSION
## -> env.PRERELEASE
## -> env.SOURCE_BRANCH
## -> env.SOURCE_SHA
## -> env.TARGET_BRANCH
## -> env.TARGET_SHA
