name: 'setup-ci'
description: ''
runs:
  using: composite
  steps:
    - uses: KamaranL/actions/setup@HEAD
      with:
        fetch-depth: 0

    - uses: gittools/actions/gitversion/setup@v0.11
      with:
        versionSpec: '5.x'

    - uses: gittools/actions/gitversion/execute@v0.11
      with:
        useConfigFile: true
        configFilePath: '${{ github.action_path }}/GitVersion.yml'

    - if: github.base_ref == 'main' && startsWith(github.head_ref, 'dev')
      run: |
        {
            # check for previous tags/releases
            if ! git describe --tags --abbrev=0 >/dev/null 2>&1 &&
                ! gh release view >/dev/null 2>&1; then
                echo "CI_VERSION=1.0.0" >>"$GITHUB_ENV"
            else
                echo "CI_VERSION=$GitVersion_MajorMinorPatch" >>"$GITHUB_ENV"
            fi
            echo "CI_BRANCH=$GITHUB_HEAD_REF" >>"$GITHUB_ENV"
        }; :
      shell: bash

    - if: github.base_ref != 'main'
      run: |
        {
            echo "CI_VERSION=$GitVersion_FullSemVer" >>"$GITHUB_ENV"
            echo "CI_BRANCH=$GITHUB_HEAD_REF" >>"$GITHUB_ENV"
        }; :
      shell: bash
