name: setup-ci
description: ''
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      id: pre
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}

    - uses: gittools/actions/gitversion/setup@v0.13
      with:
        versionSpec: 5.x

    - uses: gittools/actions/gitversion/execute@v0.13
      with:
        disableCache: true
        disableNormalization: true
        useConfigFile: true
        configFilePath: "'${{ github.action_path }}/GitVersion.yml'"
        overrideConfig: "'${{ steps.pre.outputs.gitversion-execute_overrideConfig }}'"

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash

    # - run: |
    #     { # set CI_VERSION (default)
    #         echo "CI_VERSION=$GitVersion_MajorMinorPatch" >>"$GITHUB_ENV"
    #     }; :
    #   shell: bash

    # - if: fromJson(steps.checks.outputs.github).is-prerelease == true
    #   run: |
    #     { # append prerelease tag
    #         echo "CI_VERSION=$CI_VERSION-alpha.$GitVersion_CommitsSinceVersionSource" >>"$GITHUB_ENV"
    #     }; :
    #   shell: bash

    # - if: |
    #     fromJson(steps.checks.outputs.github).is-prerelease == true &&
    #         fromJson(inputs.nuget) == true
    #   run: |
    #     { # format prerelease tag as nuget-compatible
    #         echo "CI_VERSION=${CI_VERSION%.*}${CI_VERSION##*.}" >>"$GITHUB_ENV"
    #     }; :
    #   shell: bash

    # - if: |
    #     fromJson(steps.checks.outputs.github).is-release == true &&
    #         fromJson(steps.checks.outputs.github).first-release == true
    #   run: |
    #     { # overwrite CI_VERSION for first major release
    #         echo "CI_VERSION=1.0.0" >>"$GITHUB_ENV"
    #     }; :
    #   shell: bash

    # - run: |
    #     { # set CI_SOURCE_BRANCH
    #         echo "CI_SOURCE_BRANCH=$GITHUB_HEAD_REF" >>"$GITHUB_ENV"
    #     }; :
    #   shell: bash

    # - run: |
    #     { # announce CI vars
    #         echo -e "branch:\t\t$CI_SOURCE_BRANCH"
    #         echo -e "version:\t\t$CI_VERSION"
    #     }; :
    #   shell: bash
