name: setup-ci
description: ''
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      id: pre

    - uses: gittools/actions/gitversion/setup@v0.13
      with:
        versionSpec: 5.x

    - uses: gittools/actions/gitversion/execute@v0.13
      with:
        target-path: ${{ runner.temp }}
        disableCache: true
        useConfigFile: true
        configFilePath: ${{ github.action_path }}/GitVersion.yml
        overrideConfig: ${{ steps.pre.outputs.gitversion-execute_overrideConfig }}
        additionalArguments: ${{ steps.pre.outputs.gitversion-execute_additionalArguments }}

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      id: main
