name: 'setup'
description: ''
runs:
  using: composite
  steps:
    - run: |
        TIMEZONE="America/New_York"
        [ "$(</etc/timezone)" != "$TIMEZONE" ] &&
            sudo timedatectl set-timezone "$TIMEZONE"
        ! git status >/dev/null 2>&1 &&
            echo "checkout-repo=true" >>"$GITHUB_OUTPUT"
        :
      shell: bash
      id: checks

    - if: steps.checks.outputs.checkout-repo == 'true'
      uses: actions/checkout@v4
