name: 'setup'
description: ''
inputs:
  fetch-depth:
    description: |
      [int]

      Default: '1'
    default: '1'

runs:
  using: composite
  steps:
    - uses: KamaranL/actions/checks@v0
      with:
        check: timezone,gh_token,repository
      id: check

    # - if: steps.check.outputs.gh_token == 'fail'
    - if: steps.check.outputs.raw == 'fail'
      uses: 1password/load-secrets-action@v1
      env:
        GH_TOKEN: op://Tokens/GitHub.kamaranl.CICD/credential

    - if: steps.check.outputs.timezone == 'fail'
      run: sudo timedatectl set-timezone "America/New_York"
      shell: bash

    - if: steps.check.outputs.repository == 'fail'
      uses: actions/checkout@v4
      with:
        token: ${{ env.GH_TOKEN }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - run: |
        echo -e "$RAW"
      shell: bash
      env:
        RAW: ${{ steps.check.outputs.raw }}
