name: 'setup'
description: ''
inputs:
  fetch-depth:
    description: ''
    default: '1'
  op-service-account-token:
    description: ''

runs:
  using: composite
  steps:
    - uses: KamaranL/actions/checks@v0
      with:
        github: |
          timezone-set
          has-token
          has-repository
      id: checks

    - if: fromJson(steps.checks.outputs.github).timezone-set == false
      run: sudo timedatectl set-timezone "America/New_York"
      shell: bash

    - if: fromJson(steps.checks.outputs.github).has-token == false
      uses: 1password/load-secrets-action/configure@v1
      with:
        service-account-token: ${{ inputs.op-service-account-token }}

    - if: fromJson(steps.checks.outputs.github).has-token == false
      uses: 1password/load-secrets-action@v1
      env:
        GH_TOKEN: op://Tokens/GitHub.kamaranl.CICD/credential
        SSH_ID: 'op://Private/bot@kamaranl.vip/private key'
        SSH_ID_PUB: 'op://Private/bot@kamaranl.vip/public key'

    - if: |
        fromJson(steps.checks.outputs.github).has-repository == false
      uses: actions/checkout@v4
      with:
        token: ${{ env.GH_TOKEN }}
        fetch-depth: ${{ inputs.fetch-depth }}
