name: 'setup'
description: ''
inputs:
  fetch-depth:
    description: ''
    default: '1'

runs:
  using: composite
  steps:
    - uses: KamaranL/actions/checks@v0
      with:
        github: |
          timezone-set
          has-token
          has-repository
      id: checks

    - if: fromJson(steps.checks.outputs.github).timezone-set == false
      run: sudo timedatectl set-timezone "America/New_York"
      shell: bash

    - if: fromJson(steps.checks.outputs.github).has-token == false
      uses: 1password/load-secrets-action@v1
      env:
        GH_TOKEN: op://Tokens/GitHub.kamaranl.CICD/credential

    - if: |
        fromJson(steps.checks.outputs.github).has-repository == false &&
            ${{ contains(env, 'GH_TOKEN') }}
      uses: actions/checkout@v4
      with:
        token: ${{ env.GH_TOKEN }}
        fetch-depth: ${{ inputs.fetch-depth }}
