name: 'setup'
description: ''
inputs:
  fetch-depth:
    description: '[number]'
    default: ${{ 1 }}

runs:
  using: composite
  steps:
    - uses: KamaranL/actions/checks@v0
      with:
        github: timezone-set
        # all: true
        # github: |
        #   timezone-set
        #   has-token
        #   has-repository
        # git: |
        #   has-keypair
      id: checks

    - run: |
        # cat "$RUNNER_TEMP/.json/github.json"
        echo "${{ toJson(steps.checks.outputs) }}"
        exit 128
      shell: bash

    # echo "${{ steps.checks.outputs }}"
    # echo "${{ fromJson(steps.checks.outputs.github).timezone-set }}"

    # - if: steps.check.outputs.gh_token == 'fail'
    # - if: fromJson(steps.check.outputs.raw.gh_token)
    #   uses: 1password/load-secrets-action@v1
    #   env:
    #     GH_TOKEN: op://Tokens/GitHub.kamaranl.CICD/credential

    # - if: steps.check.outputs.timezone == 'fail'
    #   run: sudo timedatectl set-timezone "America/New_York"
    #   shell: bash

    # - if: steps.check.outputs.repository == 'fail'
    #   uses: actions/checkout@v4
    #   with:
    #     token: ${{ env.GH_TOKEN }}
    #     fetch-depth: ${{ inputs.fetch-depth }}

    # - run: |
    #     echo -e "$RAW"
    #   shell: bash
    #   env:
    #     RAW: ${{ steps.check.outputs.raw }}
