name: 'checks'
description: ''
inputs:
  check:
    description: |
      [string[]] {timezone,gh_token,repository,tags_releases,all}

      Default: 'all'
    default: 'all'

outputs:
  github:
    value: |
      {
        "timezone-set": ${{ steps.github_timezone-set.outputs.value }},
        "has-token": "",
        "has-repository": "",
        "first-release": ""
      }
    description: ''

runs:
  using: composite
  steps:
    - if: contains(inputs.check, 'github_timezone-set') || inputs.check == 'all'
      run: |
        {
            [ "$(</etc/timezone)" != "America/New_York" ] &&
                echo "value=false" >>"$GITHUB_OUTPUT" ||
                echo "value=true" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash
      id: github_timezone-set

    - if: contains(inputs.check, 'github_has-token') || inputs.check == 'all'
      run: |
        {
            [ -z "$GH_TOKEN" ] &&
                echo "value=fail" >>"$GITHUB_OUTPUT" ||
                echo "value=true" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash
      id: github_has-token

    - if: contains(inputs.check, 'github_has-repository') || inputs.check == 'all'
      run: |
        {
            ! git status >/dev/null 2>&1 &&
                echo "value=fail" >>"$GITHUB_OUTPUT" ||
                echo "value=true" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash
      id: github_has-repository

    - if: contains(inputs.check, 'github_first-release') || inputs.check == 'all'
      run: |
        {
            if ! git describe --tags --abbrev=0 >/dev/null 2>&1 && ! gh release view >/dev/null 2>&1; then
                echo "value=fail" >>"$GITHUB_OUTPUT" ||
                echo "value=true" >>"$GITHUB_OUTPUT"
            fi
        }; :
      shell: bash
      id: github_first-release
