name: 'checks'
description: ''
inputs:
  checks:
    description: |
      {timezone,gh_token,repository}

      Default: 'all'
    default: 'all'

outputs:
  timezone:
    value: steps.timezone.outputs.check
    description: ''
  gh_token:
    value: steps.gh_token.outputs.check
    description: ''
  repository:
    value: steps.repository.outputs.check
    description: ''

runs:
  using: composite
  steps:
    - if: contains(inputs.checks, 'timezone') || inputs.checks == 'all'
      run: |
        {
            [ "$(</etc/timezone)" != "America/New_York" ] &&
                echo "check=fail" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash
      id: timezone

    - if: contains(inputs.checks, 'gh_token') || inputs.checks == 'all'
      run: |
        {
            [ -z "$GH_TOKEN" ] &&
                echo "check=fail" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash
      id: gh_token

    - if: contains(inputs.checks, 'repository') || inputs.checks == 'all'
      run: |
        {
            ! git status >/dev/null 2>&1 &&
                echo "check=fail" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash
      id: repository
