name: checks
description: ''
inputs:
  all:
    description: |
        [true, false]
  git:
    description: |
      ["has-keypair",
      "is-configured"]
  github:
    description: |
      ["timezone-set",
      "has-token",
      "has-repository",
      "release",
      "ci-label"]

outputs:
  git:
    value: ${{ steps.entrypoint.outputs.git }}
    description: ''
  github:
    value: ${{ steps.entrypoint.outputs.github }}
    description: ''
  path:
    value: ${{ steps.entrypoint.outputs.path }}
    description: ''

runs:
  using: composite
  steps:
    # - run: |
    #     echo "${{ toJson(inputs) }}"
    #   shell: bash

    - run: |
        \
            INPUT_ALL=${{ inputs.all }} \
            INPUT_GIT='${{ inputs.git }}' INPUT_GIT=($INPUT_GIT) \
            INPUT_GITHUB='${{ inputs.github }}' INPUT_GITHUB=($INPUT_GITHUB) \
            $GITHUB_ACTION_PATH/${GITHUB_ACTION_PATH##*\/}
      shell: bash
      id: entrypoint

