name: checks
description: ''
inputs:
  all:
    description: |
        [true, false]
  github:
    description: |
      ["timezone-set",
      "has-token",
      "has-repository",
      "release",
      "ci-label"]
  git:
    description: |
      ["has-keypair",
      "is-configured"]

outputs:
  github:
    value: ${{ steps.json.outputs.github }}
    description: ''
  git:
    value: ${{ steps.json.outputs.git }}
    description: ''
  path:
    value: ${{ steps.json.outputs.path }}
    description: ''

runs:
  using: composite
  steps:
    - run: echo '${{ fromJson(inputs) }}'
      shell: bash
