name: 'checks'
description: ''
inputs:
  checks:
    description: |
      {timezone,gh_token,repository}

      Default: 'all'
    default: 'all'

runs:
  using: composite
  steps:
    - if: contains(inputs.checks, 'timezone') || inputs.checks == 'all'
      run: |
        {
            [ "$(</etc/timezone)" != "America/New_York" ] &&
                echo "check-timezone=fail" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash

    - if: contains(inputs.checks, 'gh_token') || inputs.checks == 'all'
      run: |
        {
            [ -z "$GH_TOKEN" ] &&
                echo "check-gh_token=fail" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash

    - if: contains(inputs.checks, 'repository') || inputs.checks == 'all'
      run: |
        {
            ! git status >/dev/null 2>&1 &&
                echo "check-repository=fail" >>"$GITHUB_OUTPUT"
        }; :
      shell: bash
