#!/bin/bash

declare -A out
: \
    ${INPUT_ALL:=false}
# ${INPUT_GIT:=false} \
# ${INPUT_GITHUB:=false}

[ ! -z "$INPUT_GIT" ] && INPUT_GIT=($INPUT_GIT)
[ ! -z "$INPUT_GITHUB" ] && INPUT_GITHUB=($INPUT_GITHUB)

outputs=(
    git
    github
    path
)

echo "$INPUT_ALL"
echo "${#INPUT_GIT[@]}"
echo "${INPUT_GIT[@]}"
echo "${#INPUT_GITHUB[@]}"
echo "${INPUT_GITHUB[@]}"

for name in "${outputs[@]}"; do out[$name]="{"; done

for check in "${INPUT_GIT[@]}"; do
    :
done

for check in "${INPUT_GITHUB[@]}"; do
    [ "$check" == timezone-set ] || $INPUT_ALL && {
        echo -n "->check(github.$check)"
        [ "$(</etc/timezone)" != "America/New_York" ] && val=false
        out[github]+=" \"$check\": ${val:-true},"

    }
done

# [[ $INPUT_GITHUB =~ timezone-set ]] || $INPUT_ALL && {
#     echo "->check(github.timezone-set)"
#     [ "$(</etc/timezone)" != "America/New_York" ] && val=false
#     out[github]+=" \"timezone-set\": ${val:-true},"
# } && unset val

# [[ $INPUT_GITHUB =~ has-token ]] || $INPUT_ALL && {
#     echo "->check(github.has-token)"
#     [ -z "$GH_TOKEN" ] && val="false"
#     out[github]+=" \"has-token\": ${val:-true},"
# } && unset val

# [[ $INPUT_GITHUB =~ has-repository ]] || $INPUT_ALL && {
#     echo "->check(github.has-repository)"
#     ! git status >/dev/null 2>&1 && val="false"
#     out[github]+=" \"has-repository\": ${val:-true},"
# } && unset val

# [[ $INPUT_GITHUB =~ release ]] || $INPUT_ALL && {
#     echo "->check(github.has-repository)"
#     ! git status >/dev/null 2>&1 && val="false"
#     out[github]+=" \"has-repository\": ${val:-true},"
# } && unset val

# [[ $INPUT_GITHUB =~ has-repository ]] || $INPUT_ALL && {
#     echo "->check(github.has-repository)"
#
#     out[github]+=" \"has-repository\": ${val:-true},"
# } && unset val

for name in "${outputs[@]}"; do
    echo "$name=${out[$name]%,*} }" >>"$GITHUB_OUTPUT"
done

exit 0
