#!/bin/bash

declare -A out

: ${INPUT_ALL:=false}
INPUT_GIT=($INPUT_GIT)
INPUT_GITHUB=($INPUT_GITHUB)

outputs=(
    git
    github
    path
)

# INPUT_ALL=true

for name in "${outputs[@]}"; do out[$name]="{"; done

for check in "${INPUT_GIT[@]}"; do
    :
    echo checking "$check"
done

for check in "${INPUT_GITHUB[@]}"; do
    echo "->check(github.$check)"

    [ "$check" == timezone-set ] && {
        [ "$(</etc/timezone)" != "America/New_York" ] && val=false
    }

    [ "$check" == has-token ] && {
        [ -z "$GH_TOKEN" ] && val=false
    }

    [ "$check" == has-repository ] && {
        ! git status >/dev/null 2>&1 && val=false
    }

    [ "$check" == first-release ] && {
        if git describe --tags --abbrev=0 >/dev/null 2>&1 &&
            gh release view --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
            val=false
        fi
    }

    [ "$check" == is-prerelease ] && {
        if [ "${GITHUB_BASE_REF:-github.base_ref}" == main ] &&
            [[ ${GITHUB_HEAD_REF:-github.head_ref} =~ ^dev(elop)?(ment)?$ ]]; then
            val=false
        fi
    }

    out[github]+=" \"$check\": ${val:-true},"
    unset val
done

for name in "${outputs[@]}"; do
    echo "$name=${out[$name]%,*} }" >>"$GITHUB_OUTPUT"
done

exit 0
