name: get-context
description: ''
inputs:
  context:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - run: echo -e "$GITHUB_CONTEXT" | sed 's/^/(github)..../'
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
