name: ci
description: ''
outputs:
  ci-tag:
    value: ${{ steps.commit.outputs.tag }}
    description: ''

runs:
  using: composite
  steps:
    - if: github.event_name != 'pull_request'
      run: echo "::error::${{ github.action_repository }} can only run on \"pull_request\""; exit 128
      shell: bash

    - uses: KamaranL/actions/setup/identity@v0

    - run: |
        : # amend commit
        echo "->commit()"
        git commit -a --amend --no-edit --date=now && {
            CI_SHA="$(git rev-parse HEAD)"
            echo "sha=$CI_SHA" >>"$GITHUB_OUTPUT"
            echo "origin=$CI_SHA:$CI_SOURCE_BRANCH" >>"$GITHUB_OUTPUT"
            echo "tag=v$CI_VERSION" >>"$GITHUB_OUTPUT"
        }
      shell: bash
      id: commit

    - if: steps.commit.outputs.tag == null
      run: echo "::error::Failed to commit changes"; exit 128
      shell: bash

    - if: steps.commit.outputs.tag
      run: |
        : # create tag
        echo "->tag(${{ steps.commit.outputs.tag }})"
        git tag -a '${{ steps.commit.outputs.tag }}' -m '${{ steps.commit.outputs.tag }}' '${{ steps.commit.outputs.sha }}'
      shell: bash

    - run: |
        : # push back to source
        echo "->push(${{ steps.commit.outputs.origin }})"
        git push origin '${{ steps.commit.outputs.origin }}' --force-with-lease
      shell: bash

    - run: |
        : # comment release link
        gh pr comment '${{ github.event.number }}' --body "Published release can be found at https://github.com/$GITHUB_REPOSITORY/releases/latest"
      shell: bash
