name: setup-job
description: ''
inputs:
  ref:
    description: 'ref for actions/checkout'
  fetch-depth:
    description: 'fetch-depth for actions/checkout'
  no-repo:
    description: ''
    default: 'false'

runs:
  using: composite
  steps:
    - run: |
        \
            $GITHUB_ACTION_PATH/check.sh
      shell: bash
      id: checks

    - if: fromJson(steps.checks.outputs.timezone-set) == false
      run: sudo timedatectl set-timezone "America/New_York"
      shell: bash

    - if: fromJson(steps.checks.outputs.gh-token) == false
      uses: 1password/load-secrets-action@v1
      env:
        GH_TOKEN: op://Integrations/GitHub.kamaranl.CICD/credential

    - if: |
        fromJson(steps.checks.outputs.checked-out) == false &&
            fromJson(inputs.no-repo) == false
      uses: actions/checkout@v4
      with:
        token: ${{ env.GH_TOKEN }}
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: true
