## cd
name: github-release
description: |
  Create release for version tagged in pull_request from triggering workflow and attach assets.
inputs:
  assets:
    description: |
      Directory path containing assets to upload with release

## requires:
## <- env.GH_TOKEN
## <- env.CI_TAG
## <- KamaranL/actions/setup: [checkout, release]

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash

    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        INPUTS_ASSETS: ${{ inputs.assets }}
