name: setup-identity
description: ''
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      id: pre

    - if: fromJson(steps.pre.outputs.configured) == false
      uses: 1password/load-secrets-action@v1
      with:
        export-env: false
      env:
        id: op://Integrations/ssh-keypair.bot_kamaranl.vip/private-key
        id_pub: op://Integrations/ssh-keypair.bot_kamaranl.vip/public-key
      id: op-ssh

    - if: |
        fromJson(steps.pre.outputs.configured) == false &&
            steps.op-ssh.outputs.id &&
            steps.op-ssh.outputs.id_pub
      run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        SSH_ID: ${{ steps.op-ssh.outputs.id }}
        SSH_ID_PUB: ${{ steps.op-ssh.outputs.id_pub }}
      id: main
