## ci
name: setup/identity
description: |
  Install ssh keypair used for commit/tag signing and configure Git identity.

## requires:
## <- env.OP_SERVICE_ACCOUNT_TOKEN

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/pre.sh
      shell: bash
      id: pre

    - if: fromJson(steps.pre.outputs.configured) == false
      uses: KamaranL/1password-load-secrets-action@v1
      with:
        export-env: false
      env:
        key: op://Integrations/ssh-keypair.bot_kamaranl.vip/private-key
        key_pub: op://Integrations/ssh-keypair.bot_kamaranl.vip/public-key
      id: op-ssh

    - if: |
        fromJson(steps.pre.outputs.configured) == false &&
            steps.op-ssh.outputs.key &&
            steps.op-ssh.outputs.key_pub
      run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        SSH_KEY: ${{ steps.op-ssh.outputs.key }}
        SSH_KEY_PUB: ${{ steps.op-ssh.outputs.key_pub }}
