name: dump-context
description: ''
runs:
  using: composite
  steps:
    - if: github
      run: echo -e "$GITHUB_CONTEXT" | sed 's/^/(github).../'
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - if: env
      run: echo -e "$ENV_CONTEXT" | sed 's/^/(env).../'
      shell: bash
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
